FROM php:7.2-fpm-alpine
MAINTAINER GuHao <378999587@qq.com>

ENV TZ=Asia/Shanghai

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

ADD ./pecl /usr/local/etc/php/pecl

RUN apk update && apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        curl-dev \
        imagemagick-dev \
        libtool \
        libxml2-dev \
        postgresql-dev \
        sqlite-dev \
	    libmcrypt-dev \
	    libmcrypt \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
    && apk add --no-cache \
        curl \
        git \
        postgresql-libs \
    && pecl install -o -f redis \
    && pecl install imagick \
    && pecl install xdebug \
    && docker-php-ext-enable imagick redis xdebug \
    && docker-php-ext-install \
        curl \
        mbstring \
        mysqli \
        pdo \
        pdo_mysql \
        pdo_pgsql \
        pdo_sqlite \
        pcntl \
        tokenizer \
        xml \
        zip \
        swoole \
	&& docker-php-ext-install -j"$(getconf _NPROCESSORS_ONLN)" iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j"$(getconf _NPROCESSORS_ONLN)" gd \
    && git clone https://github.com/swoole/swoole-src.git \
    && cd swoole-src \
    && /usr/local/bin/phpize && ./configure && make && make install \
    && cd .. && rm -rf swoole-src \
    && apk del --purge git \
    && docker-php-ext-enable swoole \
    && rm -rf /tmp/pear

ADD ./laravel.ini /usr/local/etc/php/conf.d
ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/

ADD ./shopnc/shopnc.so /usr/local/lib/php/extensions/no-debug-non-zts-20170718/
ADD ./shopnc/shopnc.ini /usr/local/etc/php/conf.d/

RUN cd /usr/local/etc/php \
    && mv php.ini-development php.ini

WORKDIR /data/www

CMD ["php-fpm"]

EXPOSE 9000
