FROM php:fpm-alpine
MAINTAINER GuHao <378999587@qq.com>

ENV TZ=Asia/Shanghai

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories

ADD ./pecl /usr/local/etc/php/pecl

RUN apk update && apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        curl-dev \
        imagemagick-dev \
        libtool \
        libxml2-dev \
        postgresql-dev \
        sqlite-dev \
	    libmcrypt-dev \
	    libmcrypt \
        freetype-dev \
        libjpeg-turbo-dev \
        libpng-dev \
    && apk add --no-cache \
        curl \
        git \
        imagemagick \
        mysql-client \
        postgresql-libs \
    && pecl install /usr/local/etc/php/pecl/imagick-3.4.3.tgz \
    && pecl install /usr/local/etc/php/pecl/mcrypt-1.0.1.tgz \
    && docker-php-ext-enable mcrypt \
    && docker-php-ext-enable imagick \
    && docker-php-ext-install \
        curl \
        mbstring \
        mysqli \
        pdo \
        pdo_mysql \
        pdo_pgsql \
        pdo_sqlite \
        pcntl \
        tokenizer \
        xml \
        zip \
	&& docker-php-ext-install -j"$(getconf _NPROCESSORS_ONLN)" iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j"$(getconf _NPROCESSORS_ONLN)" gd \
    && pecl install -o -f /usr/local/etc/php/pecl/redis-4.1.1.tgz \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis \
    && pecl install /usr/local/etc/php/pecl/xdebug-2.6.1.tgz \
    && docker-php-ext-enable xdebug \
    && git clone https://github.com/php/pecl-search_engine-solr.git --depth=1 \
    && cd pecl-search_engine-solr \
    && /usr/local/bin/phpize && ./configure && make && make install \
    && cd .. && rm -rf pecl-search_engine-solr \
    && apk del --purge git \
    && docker-php-ext-enable solr

ADD ./laravel.ini /usr/local/etc/php/conf.d
ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/

ADD ./shopnc/shopnc.so /usr/local/lib/php/extensions/no-debug-non-zts-20170718/
ADD ./shopnc/shopnc.ini /usr/local/etc/php/conf.d/

RUN cd /usr/local/etc/php \
    && mv php.ini-development php.ini

WORKDIR /data/www

CMD ["php-fpm"]

EXPOSE 9000
